### ISSUE TITLE
Reverse order of services in compose file

### ISSUE THREAD

**Issue by brunoborges** [rafabene/devops-demo#1]
If you reverse the ordering of the services in the compose file, Docker Compose will create the last first. No need to use "links".

**Comment by rafabene** [comment]
I've tried it but didn't work. 

I'll keep this issue opened until https://github.com/docker/compose/issues/374 gets fixed

File under discussion: https://github.com/rafabene/devops-demo/blob/master/swarm/docker-compose.yml#L19-L22

**Comment by rafabene** [comment]
I was able to "solve" it by having both images
